{{- if .Values.functions.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supabase.functions.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.functions.environment | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supabase.functions.fullname" . }}-index-ts
data:
  index.ts: |-
{{ .Files.Get "files/functions-index.ts" | indent 4}}
{{- end }}
---
