{{- if .Values.functions.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.functions.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  {{- if not .Values.functions.autoscaling.enabled }}
  replicas: {{ .Values.functions.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "supabase.functions.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.functions.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "supabase.functions.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.functions.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "supabase.functions.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.functions.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "supabase.functions.name" $ }}
          securityContext:
            {{- toYaml .Values.functions.securityContext | nindent 12 }}
          image: "{{ .Values.functions.image.repository }}:{{ .Values.functions.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.functions.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.functions.environment }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ include "supabase.functions.fullname" $ }}
                  key: {{ $key }}
            {{- end }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.jwt.secretName }}
                  key: secret
            - name: SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.jwt.secretName }}
                  key: anonKey
            - name: SUPABASE_SERVICE_ROLE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.jwt.secretName }}
                  key: serviceKey
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName }}
                  key: password
            - name: SUPABASE_DB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName }}
                  key: url
              # value: postgresql://postgres:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
          args: ["start", "--main-service", "/home/deno/functions/main"]

          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          {{- with .Values.functions.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.functions.persistence.enabled }}
            - mountPath: /home/deno/functions
              name: function-data
          {{- end }}
            - mountPath: /home/deno/functions/main/index.ts
              name: index-ts
              subPath: index.ts
          {{- with .Values.functions.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: index-ts
          configMap:
            name: {{ include "supabase.functions.fullname" . }}-index-ts
            defaultMode: 0777
            items:
            - key: index.ts
              path: index.ts
        {{- if .Values.functions.persistence.enabled }}
        - name: function-data
          persistentVolumeClaim:
            claimName: {{ include "supabase.functions.fullname" . }}-pvc
        {{- end }}
      {{- with .Values.functions.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.functions.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.functions.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.functions.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
